### PR TITLE
Support gnome-shell 3.38

### PR DESCRIPTION
**Pull request by jubnzv**
This project seems to be abandoned. Anyway, here are my quick fixes, that make it work with gnome-shell 3.38.
I hope this is useful to someone.

### CODE REVIEW

**Comment by rhertzog** [comment]
Hi @jubnzv, the maintainer said a long time ago that he was no longer using the extension but nobody stepped forward to adopt it. But @olebowle continued to merge the occasional fixup... on my side I have also pushed fixes to the Debian package that I should have forwarded here but that I haven't.

Thanks for your pull request I used it for the Debian package. However it's not 100% clean as it does generate quite some noise in the logs (I paste only two samples but it generates many more of each on different lines of code).
```
oct. 25 16:23:01 x260-buxy gnome-shell[60959]: JS WARNING: [/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js 110]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
oct. 25 16:23:01 x260-buxy gnome-shell[60959]: Usage of object.actor is deprecated for Slider
                                               get@resource:///org/gnome/shell/ui/environment.js:314:29
                                               _buildTimerMenu@/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js:261:9
                                               wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                               _init@/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js:179:14
                                               wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                               enable@/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js:421:17
                                               _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                               loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
                                               _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
                                               collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                               _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
                                               _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
                                               _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
                                               init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                               _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
                                               start@resource:///org/gnome/shell/ui/main.js:159:5
                                               @<main>:1:47
```

@olebowle You should consider offering commit rights to those who submit PR to see if you can find a maintainer replacing you. :-)

**Comment by rhertzog** [comment]
FWIW, I have created a fork of gnome-shell-timer where I merged the other PR request that was open and it had all the fixes required for GNOME 3.38 as well (and it fixed the warnings I pointed above). I also merged some other pending changes that I had in the Debian package.

I won't spend much time on the extension but I will gladly review and merge contributions like yours in the future to keep it working with the latest GNOME releases.

I can even grant you commit rights if you are interested.

It's over here: https://github.com/rhertzog/gnome-shell-timer
