### ISSUE TITLE
Prints 3 warnings per second while timer is on with GNOME 3.18

### ISSUE THREAD

**Issue by rhertzog** [olebowle/gnome-shell-timer#29]
Forwarding a bug report I got in Debian:
https://bugs.debian.org/805347

When the timer is on, I get the following three warnings once a second
printed into the user journal or to ~/.xsession-errors.
```
pabs@chianamo ~ $ journalctl -f --user
-- Logs begin at Wed 2015-04-15 08:46:04 AWST. --
Nov 17 15:13:59 chianamo gnome-session[2178]: Indicator.prototype._draw@/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js:281
Nov 17 15:14:00 chianamo gnome-session[2178]: (gnome-shell:2243): Gjs-WARNING **: JS ERROR: TypeError: light.from_string is not a function
Nov 17 15:14:00 chianamo gnome-session[2178]: arc@/usr/share/gnome-shell/extensions/timer@olebowle.gmx.com/extension.js:262
```

**Comment by olebowle** [comment]
Does drawing an arc (pie diagram of elapsed vs. running time) next to the time work at all in the latest versions? If not you could simply try to comment [L281](https://github.com/olebowle/gnome-shell-timer/blob/master/timer%40olebowle.gmx.com/extension.js#L281) as a workaround.

**Comment by rhertzog** [comment]
No, indeed, the pie diagram seems to be gone...

**Comment by rhertzog** [comment]
Please find a patch for this issue: [patch.txt](https://github.com/olebowle/gnome-shell-timer/files/234731/patch.txt)

At the same time you can mark it as working with GNOME 3.20.
